disabled = false
languageCode = "zh-CN"
languageName = "中文"
weight = 1
title = "晚风"

[params]
  displayName = "中文"
  isoCode = "zh-CN"
  rtl = false
  dateFormat = "2 January 2006"
  # logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  # description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"

 [params.author]
   name = "南冠客"
   email = "icarusevanna@gmail.com"
#   image = "img/blowfish_logo.png"
  # imageQuality = 96
   headline = "I'm not human"
   bio = "A little bit about you"
   links = [
     { email = "mailto:alphalishqca@evannawithalkaid.beauty"  },
     { linkedin = "https://www.linkedin.com/in/evanna-zhu-191aa23a9" },
     { twitter = "https://x.com/Kirrast" }
   ]
